version: "3.5"
services:
  keycloak-dag:
    image: apozohue10/keycloak-dag
    container_name: keycloak-dag
    hostname: keycloak-dag
    networks:
      default:
        ipv4_address: 172.18.1.5
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_IMPORT=/etc/realm.json
      - KEYCLOAK_USER=admin 
      - KEYCLOAK_PASSWORD=admin
      - KEYCLOAK_LOGLEVEL=DEBUG
    volumes:
      - "./keycloak-dag/data/test-realm.json:/etc/realm.json"


  ssh-server:
    image: apozohue10/ssh-server
    hostname: ssh-server
    container_name: ssh-server
    privileged: true
    networks:
      default:
        ipv4_address: 172.18.1.6

  vault-server:
    image: apozohue10/vault-server
    container_name: vault-server
    hostname: vault-server
    networks:
      default:
        ipv4_address: 172.18.1.7
    ports:
      - "8200:8200"
    cap_add:
      - IPC_LOCK
    environment:
      - KEYCLOAK_ADDR=http://172.18.1.5:8080
      - VAULT_OIDC_CLIENT_ID=test
      - VAULT_OIDC_CLIENT_SECRET=3d2c3e59-af22-400d-8d09-2099aca7001b
      - VAULT_OIDC_SERVER_URL=http://172.18.1.5:8080/auth/realms/test
      - VAULT_REDIRECT_URIS=https://172.18.1.7:8200/v1/auth/oidc-wlcg/oidc/callback
      - VAULT_OIDC_SCOPES=openid,profile,email
    command: vault server -log-level=debug -config=/vault/config/vault.json


networks:
  default:
    ipam:
      config:
        - subnet: 172.18.1.0/24